name: aleee
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/papitas_00000.png
    - assets/images/papitas_00001.png
    - assets/images/papitas_00002.png
    - assets/images/papitas_00003.png
    - assets/images/papitas_00004.png
    - assets/images/papitas_00005.png
    - assets/images/papitas_00006.png
    - assets/images/papitas_00007.png
    - assets/images/papitas_00008.png
    - assets/images/papitas_00009.png
    - assets/images/papitas_00010.png
    - assets/images/papitas_00011.png
    - assets/images/papitas_00012.png
    - assets/images/papitas_00013.png
    - assets/images/papitas_00014.png
    - assets/images/papitas_00015.png
    - assets/images/papitas_00016.png
    - assets/images/papitas_00017.png
    - assets/images/papitas_00018.png
    - assets/images/papitas_00019.png
    - assets/images/papitas_00020.png
    - assets/images/papitas_00021.png
    - assets/images/papitas_00022.png
    - assets/images/papitas_00023.png
    - assets/images/papitas_00024.png
    - assets/images/papitas_00025.png
    - assets/images/papitas_00026.png
    - assets/images/papitas_00027.png
    - assets/images/papitas_00028.png
    - assets/images/papitas_00029.png
    - assets/images/papitas_00030.png
    - assets/images/papitas_00031.png
    - assets/images/papitas_00032.png
    - assets/images/papitas_00033.png
    - assets/images/papitas_00034.png
    - assets/images/papitas_00035.png
    - assets/images/papitas_00036.png
    - assets/images/papitas_00037.png
    - assets/images/papitas_00038.png
    - assets/images/papitas_00039.png
    - assets/images/papitas_00040.png
    - assets/images/papitas_00041.png
    - assets/images/papitas_00042.png
    - assets/images/papitas_00043.png
    - assets/images/papitas_00044.png
    - assets/images/papitas_00045.png
    - assets/images/papitas_00046.png
    - assets/images/papitas_00047.png
    - assets/images/papitas_00048.png
    - assets/images/papitas_00049.png
    - assets/images/papitas_00050.png
    - assets/images/papitas_00051.png
    - assets/images/papitas_00052.png
    - assets/images/papitas_00053.png
    - assets/images/papitas_00054.png
    - assets/images/papitas_00055.png
    - assets/images/papitas_00056.png
    - assets/images/papitas_00057.png
    - assets/images/papitas_00058.png
    - assets/images/papitas_00059.png
    - assets/images/papitas_00060.png
    - assets/images/papitas_00061.png
    - assets/images/papitas_00062.png
    - assets/images/papitas_00063.png
    - assets/images/papitas_00064.png
    - assets/images/papitas_00065.png
    - assets/images/papitas_00066.png
    - assets/images/papitas_00067.png
    - assets/images/papitas_00068.png
    - assets/images/papitas_00069.png
    - assets/images/papitas_00070.png
    - assets/images/papitas_00071.png
    - assets/images/papitas_00072.png
    - assets/images/papitas_00073.png
    - assets/images/papitas_00074.png
    - assets/images/papitas_00075.png
    - assets/images/papitas_00076.png
    - assets/images/papitas_00077.png
    - assets/images/papitas_00078.png
    - assets/images/papitas_00079.png
    - assets/images/papitas_00080.png
    - assets/images/papitas_00081.png
    - assets/images/papitas_00082.png
    - assets/images/papitas_00083.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
